[2022-12-26 19:34:05,164] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: podcast_summary2.create_table_postgres manual__2022-12-26T19:34:04.387604+00:00 [queued]>
[2022-12-26 19:34:05,177] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: podcast_summary2.create_table_postgres manual__2022-12-26T19:34:04.387604+00:00 [queued]>
[2022-12-26 19:34:05,177] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-26 19:34:05,177] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-26 19:34:05,178] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-26 19:34:05,199] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table_postgres> on 2022-12-26 19:34:04.387604+00:00
[2022-12-26 19:34:05,207] {standard_task_runner.py:52} INFO - Started process 6390 to run task
[2022-12-26 19:34:05,220] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'podcast_summary2', 'create_table_postgres', 'manual__2022-12-26T19:34:04.387604+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summer/podcast_summer2.py', '--cfg-path', '/tmp/tmpozb23uls', '--error-file', '/tmp/tmpuoiu5abq']
[2022-12-26 19:34:05,225] {standard_task_runner.py:80} INFO - Job 19: Subtask create_table_postgres
[2022-12-26 19:34:05,335] {task_command.py:369} INFO - Running <TaskInstance: podcast_summary2.create_table_postgres manual__2022-12-26T19:34:04.387604+00:00 [running]> on host 29349a459c56
[2022-12-26 19:34:05,452] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=podcast_summary2
AIRFLOW_CTX_TASK_ID=create_table_postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T19:34:04.387604+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-26T19:34:04.387604+00:00
[2022-12-26 19:34:05,478] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-12-26 19:34:05,520] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Name or service not known

[2022-12-26 19:34:05,532] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=podcast_summary2, task_id=create_table_postgres, execution_date=20221226T193404, start_date=20221226T193405, end_date=20221226T193405
[2022-12-26 19:34:05,544] {standard_task_runner.py:97} ERROR - Failed to execute job 19 for task create_table_postgres (could not translate host name "host.docker.local" to address: Name or service not known
; 6390)
[2022-12-26 19:34:05,551] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-26 19:34:05,592] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
