[2022-12-25 22:58:09,250] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: podcast_summary2.create_table_postgres manual__2022-12-25T22:58:08.660999+00:00 [queued]>
[2022-12-25 22:58:09,261] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: podcast_summary2.create_table_postgres manual__2022-12-25T22:58:08.660999+00:00 [queued]>
[2022-12-25 22:58:09,261] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-25 22:58:09,262] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-25 22:58:09,262] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-25 22:58:09,278] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table_postgres> on 2022-12-25 22:58:08.660999+00:00
[2022-12-25 22:58:09,283] {standard_task_runner.py:52} INFO - Started process 4433 to run task
[2022-12-25 22:58:09,285] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'podcast_summary2', 'create_table_postgres', 'manual__2022-12-25T22:58:08.660999+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summer/podcast_summer2.py', '--cfg-path', '/tmp/tmpc9198jlc', '--error-file', '/tmp/tmp8f6nxg08']
[2022-12-25 22:58:09,286] {standard_task_runner.py:80} INFO - Job 8: Subtask create_table_postgres
[2022-12-25 22:58:09,346] {task_command.py:369} INFO - Running <TaskInstance: podcast_summary2.create_table_postgres manual__2022-12-25T22:58:08.660999+00:00 [running]> on host 86e7070a2b3d
[2022-12-25 22:58:09,430] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=podcast_summary2
AIRFLOW_CTX_TASK_ID=create_table_postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T22:58:08.660999+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-25T22:58:08.660999+00:00
[2022-12-25 22:58:09,439] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-25 22:58:09,441] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2022-12-25 22:58:09,448] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=podcast_summary2, task_id=create_table_postgres, execution_date=20221225T225808, start_date=20221225T225809, end_date=20221225T225809
[2022-12-25 22:58:09,458] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task create_table_postgres (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 4433)
[2022-12-25 22:58:09,498] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-25 22:58:09,538] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
