[2022-12-25 22:16:21,746] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: podcast_summary2.create_table_postgres manual__2022-12-25T22:16:20.795742+00:00 [queued]>
[2022-12-25 22:16:21,756] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: podcast_summary2.create_table_postgres manual__2022-12-25T22:16:20.795742+00:00 [queued]>
[2022-12-25 22:16:21,757] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-25 22:16:21,757] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-25 22:16:21,757] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-25 22:16:21,774] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table_postgres> on 2022-12-25 22:16:20.795742+00:00
[2022-12-25 22:16:21,778] {standard_task_runner.py:52} INFO - Started process 3175 to run task
[2022-12-25 22:16:21,780] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'podcast_summary2', 'create_table_postgres', 'manual__2022-12-25T22:16:20.795742+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summer/podcast_summer2.py', '--cfg-path', '/tmp/tmp4apzbc6x', '--error-file', '/tmp/tmp4toxu_2z']
[2022-12-25 22:16:21,782] {standard_task_runner.py:80} INFO - Job 3: Subtask create_table_postgres
[2022-12-25 22:16:21,829] {task_command.py:369} INFO - Running <TaskInstance: podcast_summary2.create_table_postgres manual__2022-12-25T22:16:20.795742+00:00 [running]> on host 86e7070a2b3d
[2022-12-25 22:16:21,899] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=podcast_summary2
AIRFLOW_CTX_TASK_ID=create_table_postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T22:16:20.795742+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-25T22:16:20.795742+00:00
[2022-12-25 22:16:21,918] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2022-12-25 22:16:21,924] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=podcast_summary2, task_id=create_table_postgres, execution_date=20221225T221620, start_date=20221225T221621, end_date=20221225T221621
[2022-12-25 22:16:21,933] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task create_table_postgres (The conn_id `postgres_default` isn't defined; 3175)
[2022-12-25 22:16:21,954] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-25 22:16:21,992] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
